- hosts: servers
  become: true
  become_user: root
  tasks:
          - name: Delete a list of software from VMs ...
            apt:
                    name: "{{ packages }}"
                    state: absent
            vars:
                    packages:
                            - neofetch
