# ansible-playbook -i inventory software_add.yml

- hosts: servers
  become: true
  become_user: root
  tasks:
    - name: Add a list of software to VMs ...
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - neofetch
